name: Run unit tests

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"

      - name: Install dependenies
        run: go mod download

      - name: Run tests
        run: make test
